### ISSUE TITLE
Parametric Module Design

### ISSUE THREAD

**Issue by NGimbal** [NGimbal/sdfui#25]
**The task** 
Design a module defined by dimensional parameters, usually the value of those parameters are dictated by some outside factor.

**Frequency of this task** 
The importance and frequency of this work flow depends on the designer and whether they like to work with parametric models. For someone who likes to sketch and design this way, it could be a daily activity. For major design problems that need to be tackled by multiple parties, this might happen two or three times at the Concept - Schematic phases of a project.

**The story of this task**
The design partner has designed a wildly expensive undulating facade. A young technically minded architect, inspired by the design but afraid it will be too expensive looks for ways to rationalize the design. This architect realizes that a very similar design can be realized using a small number of repeating parts that vary in a few key dimensions. The young architect uses a tool to design a parametric model that represents this module and can flexibly illustrate the variations in type and accommodate changes as the design is refined for construction.

**How is this task accomplished now**
Tools like Grasshopper (in Rhino), the Revit Family Editor, Bentley Generative Components, Vectorworks Marionette allow designers to problem solve using parametric models.

**Necessary features**
* [x] Zoom, pan #31
* [x] Drafting of lines with specified widths, colors
* [x] Snap to points, grid, ortho to world view, angle relative to previous line, distance from pt
* [ ] Edit locations of points and lines numerically #32
* [ ] Edit position of points and lines by dimension to other prims #33
* [ ] UI for user definition of variables driven by other point locations, distances between points #34
* [ ] Edit locations of points and lines by click and drag #35
* [ ] Undo / Redo of edits #14 
* [ ] Copy / Paste of scene elements #36
* [ ] Arrange elements, (bring to front, send to back) #37
* [ ] Dimension between points #38
* [ ] Dimension between lines (parallel) #39
* [ ] Angle between lines #40
* [ ] Arc primitive #41
* [ ] Bezier  Primitive #9 

**Features that could enable efficiencies**
* [ ] Collaborative editing w/ simultaneous voice chat #42

![Geogebra Parametric](https://user-images.githubusercontent.com/34066664/79051216-fa53ea80-7bfc-11ea-8d19-cca689965f58.PNG)
![Pen and Paper Module](https://user-images.githubusercontent.com/34066664/79051219-017af880-7bfd-11ea-8c7d-8d947be67650.jpg)
![CW Pleat Dtl 01](https://user-images.githubusercontent.com/34066664/79051225-09d33380-7bfd-11ea-8e0b-86d38711b1c8.jpg)
