### ISSUE TITLE
Collaborative Design Illustration

### ISSUE THREAD

**Issue by NGimbal** [NGimbal/sdfui#27]
**The task**
Free form drawing to aid thinking and communicating to subordinates about abstract forms, perhaps with little or no respect to context or constructability. Often this involves providing feedback to designers on an ad-hoc basis.

**Frequency of this task**
For competitions and projects with high demands on the design, a single design partner can conduct these meetings 1-2 times a day for up to an hour each session.

**Story of the task**
A busy design partner has a free hour in the middle of the day to review the work of 3-10 designers. They haven't prepared design materials but take screenshots of their models that the design partner sketches over. The design partner quickly draws with gestural strokes to evoke an idea of a form or arrangement of forms to the designers. They may raise questions or concerns about ideas, but it is generally taboo for them to draw on the partner's work. They may apply a layer of trace or start another drawing to communicate their idea. These drawings are often done with markers on trace paper and layered for iteration.

**How is this task accomplished now?**
Snip and sketch over screenshots w/ screenshare, design partner dictates changes that a designer makes in realtime in 3D modeling program (Rhino), screen share over video chat w/ "request control" (sub optimal experience), PDF / image edit, attach and email back.

Necessary features
* [ ] Projects -> drawings organization structure to access different files #48 
* [ ] iPad / Apple Pencil compatible #49 
* [x] Zoom, pan #31
* [ ] Undo / Redo #14 
* [ ] Selection, transformation #36
* [ ] Copy and paste #36 
* [x] Import of images done in other software (png, pdf mainly) #44
* [x] Drafting of lines with specified widths, colors
* [ ] Freehand drawing of fills #50
* [x] Fill opacity #51
* [ ] Layers, layer arrangement / compositing #52
* [ ] Freehand erasing of scene #53
* [ ] Drawing and editing of bezier curves #9 

Features that could enable new efficiencies
* [ ] Simultaneous editing with voice chat #42 
* [ ] Layers, like layers of trace, as ui idea to show history of a drawing. #54

**Design Sketch / Parti (SH Planetarium)** 
![Planetarium_Sketch](https://user-images.githubusercontent.com/34066664/79051328-9978e200-7bfd-11ea-95f4-4b7b40a42984.PNG)

**Design Sketch for Publication (Herzog and Demuron Prada)**
![HerzogDeMuronPradaSketch](https://user-images.githubusercontent.com/34066664/79051331-9d0c6900-7bfd-11ea-9401-080200aadece.jpg)
