### ISSUE TITLE
Curtain Wall Coordination

### ISSUE THREAD

**Issue by NGimbal** [NGimbal/sdfui#30]
**The task**
Spatial coordination of elements such as glazing, structural elements, MEP ducts and piping, interior finishes, shade roller pockets.

**Frequency of this task** 
Weekly collaborative meeting starting in Schematic Design and going through Construction Documents. This period can last anywhere from 8 months to 2 years. Intensity and frequency of these meetings will vary over this period. Size of meeting can be between 3 to 15 participants around 3-10 monitors.

**The story of this task**
The design architect has an innovative design including a sculptural diagrid expressed on the exterior of the building. The structural engineers have designed a set of concrete members that are clad in a complex build up of furring, insulation and GFRC cladding. Code requires a certain area of glazing, but the nature of the building requires the glass to be a special blast resistant assembly. The facade consultant has advised that the blast resistant glazing unit can only be produced in a certain range of sizes. The MEP engineer wants 36" of plenum space for duct work and sprinkler system, but the design architect knows that will diminish the amount of glass that's left for the facade. They design a complex shade pocket that allows the plenum depth to reduce in dimension at the perimeter of the building.

**How is this task accomplished now?**
Lots of PDFs emailed back and forth, hand sketching with pen + pencil colored pencil / marker. Trace paper is used to iterate and embellish. Hand sketches are translated to 3D models and parametric models in other programs (Rhino + Grasshopper, Revit + Family Editor).

**Necessary features**
* [x] Zoom, pan #31
* [x] Import of images done in other software (png, pdf mainly) #44
* [x] Drafting of lines with specified widths, colors
* [x] Snap to points, grid, ortho to world view, angle relative to previous line, distance from pt
* [ ] Edit locations of points and lines by click and drag #35
* [ ] Trim, fillet lines, offset #45
* [ ] Undo / Redo of edits #14
* [ ] Copy / Paste of scene elements #36
* [ ] Annotation of drawings with arrows + text #46
* [ ] Hatches to indicate material #47
* [ ] Arrange elements, (bring to front, send to back) #37 
* [ ] Dimension between points #38 
* [ ] Dimension between lines (parallel) #39 
* [ ] Angle between lines #40 
* [ ] Edit lines by changing dimension between lines, angle between lines #33 

**Features that could enable efficiencies**
* [ ] Collaborative, simultaneous editing with voice chat #42 
* [ ] Propose / accept edits (i.e. pull requests, global doc suggest edits) #43

**Images by WK**
WK is a 60+ y/o architect who has an encyclopedic knowledge of curtain wall detailing. He prefers drawing by hand, but is not necessarily a luddite. Recently he has taken steps to learn how to draft in Rhino with the goal of 3D printing his details. He says he hates Revit.
<img width="815" alt="CW Elevation and Section" src="https://user-images.githubusercontent.com/34066664/79048621-61b56e80-7bec-11ea-80b2-8b57fcdec8fc.png">
<img width="1570" alt="CW Slab Edge" src="https://user-images.githubusercontent.com/34066664/79048589-392d7480-7bec-11ea-8198-dce8601bb018.png">
<img width="1553" alt="CW Shade Pocket" src="https://user-images.githubusercontent.com/34066664/79048596-3f235580-7bec-11ea-9f98-78f62d962e7c.png">
<img width="1254" alt="Fin DTL" src="https://user-images.githubusercontent.com/34066664/79051134-80236600-7bfc-11ea-8a85-49278431e205.png">

**Image by Heintges**
Heintges is an older facade consulting company who are  proficient at coordinating details in Revit.
![CW Pleat Dtl 01](https://user-images.githubusercontent.com/34066664/79051186-c7115b80-7bfc-11ea-80c5-9882a388029d.jpg)
